# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            James Paolantonio
tagline:          'Completely random thoughts'
description:      'Completely random thoughts of <a href="https://twitter.com/jPaolantonio">@jPaolantonio</a>.'
url:              http://jpaol.co
baseurl:          /

author:
  name:           'James Paolantonio'
  url:            https://twitter.com/jPaolantonio

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/jPaolantonio
linkedin:         https://www.linkedin.com/in/jamespaolantonio
